spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${your_email@gmail.com}
    password: ${your_app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8081






